language: node_js

node_js:
  - 12
  - 10
  - 8

before_install:
  - cd packages/better-dni && npm install -g yarn

after_success:
  - cd packages/better-dni && yarn benchmark
  - cd packages/better-dni && yarn coveralls
