name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/better-dni
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - run: yarn
      - run: yarn run build
      - run: yarn test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/better-dni
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: yarn
      - run: yarn run semantic-release
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
